### ISSUE TITLE
Add docs for KUBECOST_NAMESPACE env var on opencost exporter pod

### ISSUE THREAD

**Issue by cklingspor** [opencost/opencost-website#179]
As a **developer/engineer** I would like to know how to **overwrite the KUBECOST_NAMESPACE env variable** on the opencost exporter pod so the **pod not** necessarily tries to **execute in a pot. non existent namespace**. Having this in the docs would **also save time** and does **not enforce a developer/engineer** to search through **slack**.

As mentioned in [this](https://cloud-native.slack.com/archives/C03D56FPD4G/p1671114290408029) thread, I would like to extend the docs for better transparency. 
However, I'm not sure what the best place on the website would be? To me, no place sticks out here.
And, imho, also a contribution to the values.yaml of the [helm chart](https://github.com/opencost/opencost-helm-chart/blob/main/charts/opencost/values.yaml) should be made. Wdyt?

**Comment by dwbrown2** [comment]
I does seem like a valuable helm chart contribution to me! @mattray can you help here?

**Comment by mattray** [comment]
We've marked this for updating in the 1.109 release, so this variable is going to change to OPENCOST_NAMESPACE

**Comment by cklingspor** [comment]
I assume it will be documented then as well and would close the issue?

**Comment by mattray** [comment]
Yes, we will document it.
