### ISSUE TITLE
add links to logos in partner section

### ISSUE THREAD

**Issue by elenalape** [opencost/opencost-website#22]
wrap them in `<a href="..." target="_blank" rel="noopener noreferrer">...</a>`

**Comment by hs-07** [comment]
Hello @elenalape , I went through the site and readme.file as well, and found this project really an interesting one. 
I want to show my heartiest interest in contributing to this project.😊
Looking forward for a healthy  reply. 
Thank you

**Comment by dwbrown2** [comment]
@hs-07 would love to have you as a contributor! Here's general doc: https://github.com/kubecost/opencost/blob/develop/CONTRIBUTING.md

Any particular area that's of interest to you?

**Comment by hs-07** [comment]
@dwbrown2 I am a full stack developer, basically work on react js in front end and node js for backend and mongodb for database and also know docker and started learning GO Lang and interested in kubernetes.

**Comment by dwbrown2** [comment]
Awesome, Harshit! There's a handful of good first issues here: https://github.com/kubecost/opencost-website/issues

Would you want to grab any of these? Can look for more complex ones as a next step if that's of interest!

**Comment by hs-07** [comment]
@dwbrown2  sure sir... would love to find some and start contributing.

**Comment by dwbrown2** [comment]
@hs-07 looks like all good first issues were taken for now. This one might be a little bit more involved but starting just the skeleton here could be useful: https://github.com/kubecost/opencost-website/issues/31

Let me know if you'd be interested.

**Comment by hs-07** [comment]
@dwbrown2  yaa sure.... I am very much interested in exploring..😊

**Comment by mattray** [comment]
Links are there.
