### ISSUE TITLE
Multiplication symbols not displaying in the specification

### ISSUE THREAD

**Issue by jhcp** [opencost/opencost-website#258]
Hi,
while reading up on the opencost specification, I noticed that some multiplication symbols were not being rendered:
![image](https://github.com/opencost/opencost-website/assets/2080416/ccd2f2d3-c950-4d3d-877b-544dbc4bd7bf)

This happens because markdown interprets content in between asterisks as being *italics*

I'll submit a PR for this issue

**Comment by dwbrown2** [comment]
Thank you, @jhcp! Believe this is now resolved, but please feel free to reopen if more needed.
