### ISSUE TITLE
Add an enterprise support page to Opencost.io

### ISSUE THREAD

**Issue by Adam-Stack-PM** [opencost/opencost-website#31]
Add an enterprise support page to Opencost.io

According to the CNCF website guidelines, we can add a page support and direct it to Kubecost and any other providers. 

See Point 3. https://github.com/cncf/foundation/blob/main/website-guidelines.md

@dwbrown2  & @alexkubecost,If it is too soon to add this page please feel free to close out.

**Comment by mattray** [comment]
Closing in favor of https://github.com/opencost/opencost-website/issues/66
