### ISSUE TITLE
OpenCost visual table proposal

### ISSUE THREAD

**Issue by Annalillie** [opencost/opencost-website#34]
@alexkubecost reached out to me as well as a few others with the proposition of incorporating a visual table graphic on the OpenCost website to better explain its features and benefits as well as how it differs from Kubecost and its tiers. Alex and others put together a great doc [here](https://docs.google.com/spreadsheets/d/1ZaFNPDxxIDeYXy3Nwz8OwFpxqJJ5w9gQgN1HY4ZavMk/edit#gid=0) detailing this information (feel free to contribute as needed). 

The following text is from an email sent by Brett:
"My current idea for how we want to convey this information to users would come in two forms: the first would be an easily-digestible graphic which shows the four columns of products with only the most essential and key differences. This graphic would go on the main OpenCost page, and can be placed on the Welcome page for the docs. The second would be a more in-depth table, containing most of the information in this spreadsheet. We can add it as its own page in the OpenCost docs and create the table in Markdown, allowing us to add possible hyperlinks for existing documentation or expand on it as the docs grow.

I think this approach will allow us to have a promotional and simple graphic about OpenCost which can be reproduced when needed for future purposes, while also including a more information-centric yet still manageable table for users who need to scrutinize more between the products. What I'm reaching out for is general feedback/impressions, as well as what rows we should be adding to the condensed graphic. I think Purpose, Cost, Number of Nodes, and Deployment would be the main rows included.

If all of this looks good, please let me know. Otherwise, provide ideas in this chain. I would like to get first impressions by Wednesday of next week, so I can get the project moving up to speed."

**Comment by dwbrown2** [comment]
@Annalillie this looks great, but based on [CNCF website guidelines](https://github.com/cncf/foundation/blob/main/website-guidelines.md) I think we should look at posting this on Kubecost properties. Let me know what you think and if you have questions.

**Comment by Annalillie** [comment]
That sounds good to me Webb! I'll design it for Kubecost and let you know if I have any questions!
