### ISSUE TITLE
Large gap under the hero section on opencost.io

### ISSUE THREAD

**Issue by Adam-Stack-PM** [opencost/opencost-website#5]
There is a large gap between the hero section and the Cost allocation, simple & standard title. 

<img width="1531" alt="Screen Shot 2022-06-03 at 3 24 21 PM" src="https://user-images.githubusercontent.com/102822297/171955108-34c63603-2067-434b-9775-bad6ad7f2163.png">

**Comment by iswarmondal** [comment]
Hey, @AdamStack18 is this issue still open? I want to contribute to this issue.

**Comment by iswarmondal** [comment]
> @iswarmondal Thanks for your willingness to help. This issue is indeed still open. I’ve assigned you the ticket and will keep an eye out for your PR to get it reviewed and merged.

Thanks, I'll soon create a PR.

**Comment by elenalape** [comment]
thanks @iswarmondal, let us know if you need help! we'll want to make sure that the Hero spans the screen height, and the image is centered. the site uses [tailwind](https://tailwindcss.com/).

**Comment by iswarmondal** [comment]
> thanks @iswarmondal, let us know if you need help! we'll want to make sure that the Hero spans the screen height, and the image is centered. the site uses [tailwind](https://tailwindcss.com/).

Thanks, I did a PR. Please review it.
