### ISSUE TITLE
Document supported integrations

### ISSUE THREAD

**Issue by dwbrown2** [opencost/opencost-website#52]
We've had a couple people express interest in seeing the currently supported OpenCost integrations. As this number is quickly growing, I think it would be interesting to add a new docs and maybe homepage section for those that support. 

cc @alexkubecost

**Comment by mattray** [comment]
Hmmm... I think I confused "currently supported OpenCost integrations" with "currently supported Enterprise solutions". 
https://www.opencost.io/enterprise

Reopening.
