### ISSUE TITLE
Next steps for expanding OpenCost docs

### ISSUE THREAD

**Issue by bstuder99** [opencost/opencost-website#57]
Hey everyone,

Wondering what Q4 plans are currently in effect for expanding OpenCost docs, and what help I can provide. I think we made some great steps for our OpenCost installation with @jessegoodier's help, distinguishing OpenCost's installation from Kubecost wherever possible. I'm thinking we should consider what content could be exported from our Kubecost docs, and what other procedures/tutorials users have been asking for for OpenCost.

**Comment by dwbrown2** [comment]
@mattray anything you're hoping to tackle soon?

**Comment by mattray** [comment]
After dealing with https://github.com/kubecost/opencost-website/issues/45 I was going to open an issue to get us aligned with https://github.com/cncf/foundation/blob/main/charter.md#11-ip-policy, specifically
```
(f) All documentation will be received and made available by the CNCF under the Creative Commons Attribution 4.0 International License.
```

**Comment by bstuder99** [comment]
So does this mean all docs changes would have to be sent to CNCF for them to approve and publish?

**Comment by dwbrown2** [comment]
No, they don't need to approve docs changes
