### ISSUE TITLE
Create Enterprise OpenCost page

### ISSUE THREAD

**Issue by dwbrown2** [opencost/opencost-website#66]
CNCF guidelines recommend that OpenCost has a dedicated page for enterprise offerings: https://github.com/cncf/foundation/blob/main/website-guidelines.md

I believe the Cilium website provides a good example implementation: https://cilium.io/

@Annalillie has a great design proposal too

**Comment by mattray** [comment]
@Annalillie feel free to weigh in on https://github.com/opencost/opencost-website/pull/67
Thanks!
