### ISSUE TITLE
Dark mode should update the OpenCost logo

### ISSUE THREAD

**Issue by mattray** [opencost/opencost-website#75]
The footer has the proper logo for dark mode, but the original logo is still used at the top
<img width="601" alt="Screen Shot 2023-01-31 at 2 57 47 PM" src="https://user-images.githubusercontent.com/330023/215659569-eca1a0fa-b5c6-4a8c-bcd9-b4adb758f0c6.png">

**Comment by toscott** [comment]
I can grab this one.
