### ISSUE TITLE
API page in dark-mode looks mismatched

### ISSUE THREAD

**Issue by mattray** [opencost/opencost-website#85]
The theming isn't really right on the page, it looks best on normal.

<img width="1569" alt="Screenshot 2023-02-14 at 3 13 43 PM" src="https://user-images.githubusercontent.com/330023/218637694-921d4cdb-250f-4a6a-8185-2b60d7f38f63.png">

**Comment by upendrasahni** [comment]
Hey @mattray i am interested in this issue, can you assign this issue to me?

**Comment by mattray** [comment]
@upendrasahni feel free to take a pass on it and I'll review the PR. Thanks!

**Comment by mattray** [comment]
The API page has been refactored and is no longer pre-rendered.
