### ISSUE TITLE
API Usage - Error in example query 

### ISSUE THREAD

**Issue by daniwk** [opencost/opencost-website#89]
The query examples under [API Usage page](https://www.opencost.io/docs/api#/paths/~1allocation~1compute/get) contains referance to `localhost:9090`. Shouldn't this point to the API server instead, i.e. `localhost:9003`? 

Please let me know if you'd like me to create PR.

**Comment by mattray** [comment]
Good point. The source file is here if you want to make a PR: https://github.com/opencost/opencost/blob/develop/docs/swagger.json
